### ISSUE TITLE
How to install.

### ISSUE THREAD

**Issue by Oxmaster** [paveldn/haier-esphome#16]
Pardon my ignorance, but I have no clue how to flash/config this thing. I'm using ESPHome for the first time.

I want to use this repository with ESP8266 D1 Mini and as35tamhra-c, it has the ESP32-for-Haier module.

I can't find any information about using this. In read me it just says to flash ESPHome. I can't see any .bin file in this repository or anything that could be flashed. I tried the configurations from tests/esp8266-hon-wifi.yaml and wemos_d1_mini.yaml, but I'm getting errors. 

So far I've flashed the ESPHome firmware on my D1 mini via HomeAssistant and tried editing the yaml config of the module, but I'm getting error `Invalid YAML syntax: Error reading file /config/esphome/./.wifi-base.yaml: [Errno 2] No such file or directory: '/config/esphome/./.wifi-base.yaml'`. I've combined basic configuration that came with ESPHome, esp8266-hon-wifi.yaml, wemos_d1_mini.yaml and sample configuration from readme

```
substitutions:
  device_name: Haier AC
  device_id: haier_climate
  uart_id: ac_port 
  send_wifi: "true"

esphome:
  name: esphome-web-9ccdac
  friendly_name: Haier AC

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "[hidden]"

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-9Ccdac"
    password: "Wx352F0mVwL4"

captive_portal:
    
uart:
  baud_rate: 9600
  tx_pin: 1
  rx_pin: 3
  id: ${uart_id} 

external_components:
  source:
    type: local
    path: ../components

<<: !include ./.wifi-base.yaml

<<: !include ../.haier-hon-base.yaml

climate:
  - platform: haier
    id: haier_ac
    protocol: hOn
    name: Haier AC 
    uart_id: ${uart_id}
    wifi_signal: true           # Optional, default true, enables WiFI signal transmission from ESP to AC
    beeper: true                # Optional, default true, disables beep on commands from ESP
    outdoor_temperature:        # Optional, outdoor temperature sensor
      name: Haier AC outdoor temperature
    visual:                     # Optional, you can use it to limit min and max temperatures in UI (not working for remote!)
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    supported_modes:            # Optional, can be used to disable some modes if you don't need them
    - 'OFF'
    - AUTO
    - COOL
    - HEAT
    - DRY
    - FAN_ONLY
    supported_swing_modes:      # Optional, can be used to disable some swing modes if your AC does not support it
    - 'OFF'
    - VERTICAL
    - HORIZONTAL
```
