### ISSUE TITLE
Identical ESP32-for-Haier_V1.1 inside Haier Washing Machine 

### ISSUE THREAD

**Issue by Benniepie** [paveldn/haier-esphome#37]
Hello all

I've just opened up my Haier Europe HW90-B149598U1_UK Washing Machine, which uses the Hon app to have a nosey around (there goes the warranty). I've fished out an identical "ESP32-for-Haier_V1.1" board to the one you guys identified in Haier Hon AC units.

Here's my board:
![20240122_002555](https://github.com/paveldn/haier-esphome/assets/65065193/3c7b974f-bb06-4606-a0e6-ce065f4c5b69)
![20240122_004035](https://github.com/paveldn/haier-esphome/assets/65065193/55a4e27f-fde2-42ee-b06d-d5ee9e71bab8)

Enclosure:
![20240122_004133](https://github.com/paveldn/haier-esphome/assets/65065193/767fd02e-7eec-4098-bccc-78ee9833232a)

As a complete beginner in the world of Esphome, given that my device is not an AC unit, where would you advise I start? 

I have other Esp32 and Esp2866 boards available. Would you suggest substituting one of these rather than attempt to re-use the original?  How would I go about figuring out the parameters for an entirely new device? 

Would really appreciate some pointers on how to approach this as you've been here before, albeit for a different bit of kit!

Given Haier's despicable behaviour to the dev of the Hon integration, I'm motivated to find a way for Haier customers  liberate their devices from this awful company. 

Apologies If this isn't the right place to post

Kind regards 

Ben

**Comment by Benniepie** [comment]
Would perhaps a UART sniffer between the existing Haler ESP32 and the PCB to capiture traffic be a good start?

**Comment by paveldn** [comment]
Hi @Benniepie,

First of all, let me say that you are the first one with that module in non-AC equipment. I never tried to do anything with Haier's washing machines. So thanks for reaching me. 

Yes, the best way is to put a sniffer in between you will need to have two ports on your PC (or other device that will sniff) one for ESP32 -> washing machine, another for washing machine -> ESP32. It should be something like this:
![image](https://github.com/paveldn/haier-esphome/assets/11540146/60112751-fe9d-4979-a04f-8fefa8d39ddf)
Sorry, I am not good at drawing, made it for ACs but it should be the same in your case. But the first step could be even simpler you can connect Haier ESP32 to a PC and see requests. AC ESP32 devices use 9600 bps speed I expect the same in your case. In the past I was using something like this https://www.tinytronics.nl/shop/en/tools-and-mounting/measuring/accessories/test-probe-with-clamp-pogo-pin-2x5p + ttl to USB convertor to connect ESP32 to PC to avoid cutting of cables. Let me know if I can help you with something,

**Comment by Benniepie** [comment]
Thank you so much for the prompt and practical reply! 

The washing machine is only around 6 months old so this may become common place with new Haier appliances. I also have a Haier Tumble dryer which is around 3 months older than the washer but I haven't checked this one yet.

Thanks for the diagram, makes perfect sense. As my washing machine is in my bathroom, and because I havent got any USB TTL adapters (yet), I was thinking of using an Esphome ESP32 configured with 2xUART (one for the Haier ESP32 TX and one for Haier ESP32 RX) and then use WiFi connectivity and  logging to give me access to the serial data wirelessly. This way I can safely reassemble my washing machine with the sniffer ESP32 inside collecting data. Do you think this would work? There is, fortunately a convenient connector I can use to temporarily connect the sniffer to the cables between the Haier ESP32 and PCB without cutting any wires (or soldering) fortunately. 

Thank you for the bps rate info and the link to the test Probe/clamp thingy I will order it lt along with the USB TTL adapters for when I need to flash/backup the Haier ESP32.

I'm quite excited to see if this might lead to local control for Haier appliances!! 

Kind regards 

Ben

**Comment by paveldn** [comment]
@Benniepie Using ESP with 2 serial ports should work for sniffing. At least it worked for me in the past.
You came just at the right time a couple of days ago I thought that implemented everything I could for Haier ACs  and was looking for a new hobby project :smile:

**Comment by Benniepie** [comment]
> @Benniepie Using ESP with 2 serial ports should work for sniffing. At least it worked for me in the past. You came just at the right time a couple of days ago I thought that implemented everything I could for Haier ACs and was looking for a new hobby project 😄



Thank you, I can confrirm the Esp worked and Im able to capture UART comms in both directions with it. I read a lot of the document's/code in your Haier Protocol repo and it appears that my washer follows the she same protocol 99% of the time, except with laundry related data. When changing the program on the washer, for example, this is transmitted to the ESP32 as per the Haier protocol with the daya part of the frame, if converted to ascii states the wash cycle name eg "Eco 40-60", "Synthetics", "Quick". 

I have had a bit craziness with the UART data not always behaving, eg missing line breaks or extra line breaks in the middle of a frame so am working to tidy this up and see what other data (or commands). I can reverse engineer. Happy to share data etc if it is of use.

With regard to your next challenge, I'm sure adding Haier appliances to your integration would be challenge (but great timing). it would be very well received by the community if you wanted to pursue it! Im more than happy to help - i have a couple of Haier appliances as a starting point and lots of enthusiasm for a local solution (although this is all new to me so learning as I go!)

Kind regards 

Ben

**Comment by paveldn** [comment]
@Benniepie Great news! I expected something like this. Keep in mind that in the original Haier protocol used by AC (and most likely all other appliances) all 0xFF inside packet (except starting 0xFF 0xFF) should be followed by 0x55 to avoid false detection of frame start. So if you see 0xFF 0x55 inside the packet you should drop 0xFF before interpreting data. If you want me to help with analysis please share the data you collected. Also, it would be useful to see ESP's full flash image. If it is not encrypted you can get a lot of interesting things there especially if there is ASCII data included in packets.

**Comment by evlo** [comment]
from the haier site haigeek.om

https://resource.haigeek.com/ossdownload/resource/selfService/hardware/uartfile/U%2B%E5%BC%80%E6%94%BE%E5%B9%B3%E5%8F%B0washingMachineUART%E9%80%9A%E8%AE%AF%E5%8D%8F%E8%AE%AE_20240123183242466.pdf 

[U+开放平台washingMachineUART通讯协议_20240123183242466.pdf](https://github.com/paveldn/haier-esphome/files/14022342/U%2B.washingMachineUART._20240123183242466.pdf)

**Comment by finalbillybong** [comment]
This is very interesting. I have a Haier dishwasher that I would be a happy to open if this project works out and you'd need data to support.

I do like the idea of using 2 x ESP32 to capture the data - less time with the dishwasher in bits = happier wife.

If you could provide basic instructions on getting this going I would happy to supply the data I capture. I wouldn't be able to interpret it but happy to provide.

**Comment by evlo** [comment]
Why would you not just try use what is provided amd do it the hard way with sniffing and then figuring out what everything does? I do not understand.

**Comment by paveldn** [comment]
@evlo , Thanks you always have the best douments. How are you getting them? I can't find anything there. Are there any other documents regarding other types of hOn hardware? And thanks for the document you provided that is exactly what I needed.

@all, 
Let me check the document evlo provided. A quick glance shows that the protocol is almost the same, just the status frame is different but I need to check more. Anyway, I will need real communication dumps. My experience with Haier AC shows that not always everything described in the protocol document is working.  I will make a short description of how to make an ESP32-based sniffer later (probably tomorrow).

**Comment by evlo** [comment]
1. login
2. create device - basically this is to add your own appliance to haier ecosystem, so it would need to use the same protocol they use
![image](https://github.com/paveldn/haier-esphome/assets/8813196/4b4eeac0-4dd7-436a-809d-9603188bc702)
3. find the device of similar kind with the template
for dishwasher I did not find any, but i did not search a lot, but there is an option to request the template
![image](https://github.com/paveldn/haier-esphome/assets/8813196/a31cf052-c460-4b6e-81ea-409371e104e0)
this is for the fridge, when there is template it will show the properties
![image](https://github.com/paveldn/haier-esphome/assets/8813196/4c3ce045-78b7-4416-94cb-7be9754ee52c)
next page again shows it 

next page has the protocol, you need to delete 预留 data backup, if you want to download

download

![image](https://github.com/paveldn/haier-esphome/assets/8813196/9ce2b096-174b-4379-92ee-921c67873c72)

**Comment by paveldn** [comment]
Great, thanks. Never was able to get this far. 
As for the documentation, I saw it in the past, it does not add anything new to the protocol description. There is some info but not really much new.

**Comment by Benniepie** [comment]
For those with a Haier washing machine here's a pic with the Haier ESP32 location (holding the front control panel upside down). Esp32 is in the black enclosure with a green sticker.

![VideoCapture_20240123-184015](https://github.com/paveldn/haier-esphome/assets/65065193/0c009865-fb7a-4b1d-a66a-bb3de105bad7)

To access:
1) Remove lid (two screws at rear of machine then slide backwards)
2) Remove detergent drawer
3) Detach front panel (Two screws on either side of detergent drawer, four clips on top two of which have screws and then a bit of heft to detach)

The Haier ESP32 is inside the black enclosure with a green sticker. I followed the TX and RX cables from the Haier ESP32 to the connector (Haier ESP32 RX is green cable and the Haier ESP32 TX is white). 

These correspond to MCU_TX and MCU_RX on the Esp32:

![20240122_002555](https://github.com/paveldn/haier-esphome/assets/65065193/536ba1cc-9f01-4ba9-a2f8-624d08e0d83f)

I inserted extra cables into the connector (the loose cables in the pic) and hooked them up to separate RX pins on my Sniffer ESP32 running Esphome (two UART buses, 9600 baud, debug set to VERBOSE)

I have no idea if this is the best way or even a sensible way of doing it but it is working and I didn't have to cut any cables/solder.

Will do some laundry and post my data shortly.

**Comment by Benniepie** [comment]
> 1. login
> 2. create device - basically this is to add your own appliance to haier ecosystem, **so it would need to use the same protocol they use** - we already verified this is the case with AC :)
>    ![image](https://private-user-images.githubusercontent.com/8813196/299026801-4b4eeac0-4dd7-436a-809d-9603188bc702.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzU3NjcsIm5iZiI6MTcwNjAzNTQ2NywicGF0aCI6Ii84ODEzMTk2LzI5OTAyNjgwMS00YjRlZWFjMC00ZGQ3LTQzNmEtODA5ZC05NjAzMTg4YmM3MDIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTg0NDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Mjc0NDBkYjg1MDc3OGVkYWI3ODdmMGEyOTU4Y2M0OGI5YTA1MTU4YTM3ODlkMjkwMzhkMTJkYmYwMjc5YTUyOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.04DzrpBEXAM5qRASCBTL9MRMoF5m9j17acE1ndoO7As)
> 3. find the device of similar kind with the template
>    for dishwasher I did not find any, but i did not search a lot, but there is an option to request the template
>    ![image](https://private-user-images.githubusercontent.com/8813196/299029981-a31cf052-c460-4b6e-81ea-409371e104e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzU3NjcsIm5iZiI6MTcwNjAzNTQ2NywicGF0aCI6Ii84ODEzMTk2LzI5OTAyOTk4MS1hMzFjZjA1Mi1jNDYwLTRiNmUtODFlYS00MDkzNzFlMTA0ZTAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTg0NDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzA4ODcwMTI1NTUwZDAyMDZlMDA2OWMyOTQ0OWY4NzIzYTYzZjU4OWMxOWRkZDQzZDgxZmEzY2FhYzRjZmY3MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.et1tC7W9vLsfekbyVQuD47ngVzlVqSqFbTQQIPGLnp0)
> 
> but I think there might be something in some other section as the machine translations from chinese, mao's version of chinese even, are not that great
> 
> anyway I think chances of them providing the template are rather good, when I wrote with them about the old "smartAir2" they did react, just seemed they do not want to support old / Europe's Haier stuff.
> 
> ....
> 
> this is for the fridge, when there is template it will show the properties ![image](https://private-user-images.githubusercontent.com/8813196/299030342-4c3ce045-78b7-4416-94cb-7be9754ee52c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzU3NjcsIm5iZiI6MTcwNjAzNTQ2NywicGF0aCI6Ii84ODEzMTk2LzI5OTAzMDM0Mi00YzNjZTA0NS03OGI3LTQ0MTYtOTRjYi03YmU5NzU0ZWU1MmMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTg0NDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzQ5MDM1Yzc1MzU5MDVkZWQzMTEwM2FlZTY2Yjg2MjQ5MWE1NmYzMmFjNGZmZTRkOWYxYmY2MjkxMmEwMzc4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jNpEIqkf-j7wrh8bsNJdABkSIXIu8klDPVQJJG-DKZk) next page again shows the protocol (which if you were creating your own appliance, you could add your custom stuff etc.)
> 
> next page has the protocol, you need to delete 预留 / "data backup", if you want to download, as those are unused and duplicate in the spec.
> 
> ![image](https://private-user-images.githubusercontent.com/8813196/299033195-8e9cb690-9003-4482-9197-cd83934e46ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzU3NjcsIm5iZiI6MTcwNjAzNTQ2NywicGF0aCI6Ii84ODEzMTk2LzI5OTAzMzE5NS04ZTljYjY5MC05MDAzLTQ0ODItOTE5Ny1jZDgzOTM0ZTQ2ZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTg0NDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODk0MDA0Yzc3NWJjZjUwY2FiNWQyZWU2NzYyMjYwMGE0YmM2NWM2OWE2MGIwY2Q0MmI3NmI4M2Y0OWZiNThkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.fk-BELi9QDyXOjDWwPjCkfpL9JswrRQIAV6ATOzI7HY) ![image](https://private-user-images.githubusercontent.com/8813196/299033431-6941cd77-fb2f-4936-a71a-5bdbbe2970d1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzU3NjcsIm5iZiI6MTcwNjAzNTQ2NywicGF0aCI6Ii84ODEzMTk2LzI5OTAzMzQzMS02OTQxY2Q3Ny1mYjJmLTQ5MzYtYTcxYS01YmRiYmUyOTcwZDEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTg0NDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MmM1YzMyYzc1ZTkxNTk3MTE1ZTkxNDhkYzI4NjU1ZWQ0YTkwMjUxNGEyZThjMzRhMTA0MDdiNjk3YjJlOGM3NiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.yNdA4644jNDUmV9fCUXw6pLLuKBgJDe8Xgk4SPCa9Js)
> 
> **download**
> 
> ![image](https://private-user-images.githubusercontent.com/8813196/299031744-9ce2b096-174b-4379-92ee-921c67873c72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMzU3NjcsIm5iZiI6MTcwNjAzNTQ2NywicGF0aCI6Ii84ODEzMTk2LzI5OTAzMTc0NC05Y2UyYjA5Ni0xNzRiLTQzNzktOTJlZS05MjFjNjc4NzNjNzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMjNUMTg0NDI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTEwZjEwZGFjZDgzYjUyNWQ0MDhhZWQ3ODhiOTg4ZGU5ZDIwOThiZjI3ZmU3NzU5ODIxOTBmMjdlOTlkOWQxNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.1KEt2zo_TV4ZKZjsz8Iz23qKpvk5tG2SlDLDhGskh68)
> 
> hope it is understandable
> 
> I did not go trough all the docs, there is general section for devs https://www.haigeek.com/haigeekWeb/#/docs-page/?id=250 but it seems to be that in general chinese hair does not use hON, but the UART level seems to be same

Thank you so much - these docs really help!

**Comment by finalbillybong** [comment]
So I took my dishwasher to pieces just too compare what I would find to your washing machine @Benniepie.

Mine is quite different and has the ESP module mounted onto the control board. It is also marked up as ESP Gold rather than ESP for Haier. 

I do have access to the RX, TX GPIO0 and GND pins though. So I am happy to see if I can dump the contents of the chip but I will need some slight assistance with the method. 

![IMG_1636](https://github.com/paveldn/haier-esphome/assets/24855560/3c1c6499-aac3-4f03-9319-a3a013294127)
![IMG_1639](https://github.com/paveldn/haier-esphome/assets/24855560/f8ae9b28-9680-40c0-986e-8b4dab21cd3c)
![IMG_1638](https://github.com/paveldn/haier-esphome/assets/24855560/f8c3ab5b-4f4e-4751-8211-fe2e8aa52a34)

**Comment by Benniepie** [comment]
Good work @finalbillybong glad I'm not the only one crazy enough to dismantle their home appliances! interesting that it is a different chipset in yours.

The ESP32-SOLO-1 is a single core ESP32 and just needs a bit of extra config to run Esphome, so based on what little I know doesn't rule it out. It has a single UART bus so RX and TX may allow you to listen in to the UART comms as I have. As for dumping the image, I haven't got that far yet with mine but hopefully others can advise.

Do you use the Haier Hon home assistant integration? If so can you press the 'show device info' button? It will generate a notification with info about your appliance. I'm interested in what it says under 'attributes' - particularly chipset? 

Would be useful to collect this info to identify the same chipset in other appliances

E.g. for my Washing machine ESP32-For-Haier-V1.1 it says the chipset is ESP32D0WDQ5

![Screenshot_20240123_213007_Home Assistant](https://github.com/paveldn/haier-esphome/assets/65065193/af17517f-1c2c-4e10-8d2f-aa96cf967a9a)

P.s. 'for the war effort' is a great answer in more ways than one considering Haier's dubious corporate ethics 🇺🇦

**Comment by finalbillybong** [comment]
> Do you use the Haier Hon home assistant integration? If so can you press the 'show device info' button? It will generate a notification with info about your appliance. I'm interested in what it says under 'attributes' - particularly chipset?

I do! More than happy to provide that. I also have a Hover washing machine and a Candy tumble dryer that use the hOn app..... but I'll do one at a time for now. 

> Would be useful to collect this info to identify the same chipset in other appliances

> P.s. 'for the war effort' is a great answer in more ways than one considering Haier's dubious corporate ethics 🇺🇦
Yeah that was my reference but seeing as she has no idea of the Haier/Andre situation she didn't appreciate the genius of my answer /s

```
data:
  additional_data:
    options:
      opt1: threeInOne
      opt2: ecoExpress
      opt3: halfLoad
      opt4: extraDry
      opt5: openDoor
      opt6: addDish
  appliance:
    applianceId: xx-xx-xx-xx-xx-xx#2022-07-02T13:40:31Z
    applianceModelId: 874
    applianceStatus: 1
    applianceTypeId: 9
    applianceTypeName: DW
    attributes:
      acuVersion: 0.0.0
      chipset: ESP32D0WDQ5
      dictionaryId: 292
      fwLabel: nuib
      lang: it-IT
      uiVersion: 5.5.0
    brand: haier
    code: 32901553
    connectivity: wifi|ble
    eepromId: 812
    eepromName: 70010344
    enrollmentDate: 2022-07-02T13:40:31.270Z
    firstEnrollment: False
    firstEnrollmentTBC: False
    fwVersion: 5.5.0
    id: 874
    lastUpdate: 2022-07-02T13:40:42Z
    macAddress: xx-xx-xx-xx-xx-xx
    modelName: XIB 3B2SFS-80
    purchaseDate: 2022-07-01T23:00:00.000Z
    sections:
      chatbot: True
      check_up: False
      ecoDelayStart: True
      enroll_under_norms: False
      quickPair_enabled: False
    series: haier2021
    topics:
      publish:
      subscribe:
        - $aws/events/presence/disconnected/xx-xx-xx-xx-xx-xx
        - $aws/events/presence/connected/xx-xx-xx-xx-xx-xx
        - haier/things/xx-xx-xx-xx-xx-xx/event/appliancestatus/update
        - haier/things/xx-xx-xx-xx-xx-xx/event/discovery/update
  attributes:
    active: False
    activity:
    commandHistory:
      command:
        ancillaryParameters:
          ecoIndex: 4
          energyLabel: 4
          functionalId: 8
          powerWashPrz: 1
          programFamily: [hidden|guided]
          programType: WD
          remainingTime: 39
          remoteActionable: 1
          remoteVisible: 1
          suggestedLoadD: 6.5
          temp: 60
          waterEfficiency: 5
          waterSaving: 83
        applianceOptions:
          opt1: threeInOne
          opt2: ecoExpress
          opt3: halfLoad
          opt4: extraDry
          opt5: openDoor
          opt6: addDish
        applianceType: DW
        attributes:
          channel: mobileApp
          energyLabel: 0
          origin: standardProgram
        commandName: startProgram
        device:
          appVersion: 2.0.10
          deviceModel: exynos9820
          mobileId: a14582a86464a7a0
          mobileOs: android
          osVersion: 31
        macAddress: xx-xx-xx-xx-xx-xx
        parameters:
          checkUpStatus: 0
          delayTime: 0
          extraDry: 0
          halfLoad: 0
          onOffStatus: 1
          openDoor: 0
          prCode: 21
          prPosition: 13
          prStr: Rapid 39' 60°C
        timestamp: 2024-01-23T03:30:00.185Z
        transactionId: xx-xx-xx-xx-xx-xx_2024-01-23T03:30:00.185Z
      timestampAccepted: 2024-01-23T03:30:02.0Z
      timestampExecuted: 2024-01-23T03:30:03.0Z
    lastConnEvent:
      category: CONNECTED
      instantTime: 2024-01-23T20:18:02Z
      macAddress: xx-xx-xx-xx-xx-xx
      timestampEvent: 1706041082276
    parameters:
      addDish: 1
      addDishStatus: 0
      armStatus: 0
      buzzerDisabled: 0
      cameraStatus: 0
      checkUpStatus: 0
      delayTime: 0
      doorStatus: 0
      ecoExpress: 0
      errors: 00
      extraDry: 0
      halfLoad: 0
      lang: 2
      lastCycleSavingStatus: 0
      macAddressCamera: 
      machMode: 1
      openDoor: 0
      photoSessionStatus: 0
      prCode: 15
      prCodeSuggest: 0
      prPhase: 0
      prPosition: 3
      program1: 514
      program10: 18
      program11: 0
      program12: 0
      program13: 0
      program14: 0
      program15: 0
      program16: 0
      program17: 0
      program18: 0
      program19: 0
      program2: 2
      program20: 0
      program21: 0
      program3: 0
      program4: 88
      program5: 0
      program6: 1
      program7: 0
      program8: 6
      program9: 5
      remainingTimeMM: 160
      remoteCtrValid: 1
      rinseAidStatus: 0
      saltStatus: 0
      specialAutomaticStatus: 0
      temp45to55: 161
      temp60to65: 94
      temp70to75: 7
      threeInOne: 0
      waterHard: 4
    programName: auto_universal_soil
    resultCode: 0
  extra_command_data:
    startProgram:
      extraDry:
        1: 189
      halfLoad:
        1: 139
      openDoor:
        1: 225
  settings:
    custom:
      category: setParameters
    parameters:
      buzzerDisabled: 0
      lastCycleSavingStatus: 0
      waterHard: 4
  startProgram:
    ancillaryParameters:
      ecoIndex: 4
      ecoIndexOpt3: 0
      ecoIndexOpt4: 0
      ecoIndexOpt5: 0
      energyLabel: 4
      functionalId: 2
      programFamily: [dashboard|guided]
      programRules: {'opt2': {'opt3': {'1': {'typology': 'fixed', 'fixedValue': '0'}}, 'opt7': {'1': {'typology': 'fixed', 'fixedValue': '0'}}, 'opt8': {'1': {'typology': 'fixed', 'fixedValue': '0'}}, 'opt4': {'1': {'typology': 'fixed', 'fixedValue': '0'}}}, 'opt3': {'opt2': {'1': {'typology': 'fixed', 'fixedValue': '0'}}, 'opt8': {'1': {'typology': 'fixed', 'fixedValue': '0'}}}, 'opt4': {'opt2': {'1': {'typology': 'fixed', 'fixedValue': '0'}}}, 'opt7': {'opt2': {'1': {'typology': 'fixed', 'fixedValue': '0'}}}, 'opt8': {'opt2': {'1': {'typology': 'fixed', 'fixedValue': '0'}}, 'opt3': {'1': {'typology': 'fixed', 'fixedValue': '0'}}}}
      programType: WD
      remainingTime: 179
      remoteActionable: 1
      remoteVisible: 1
      suggestedLoadD: RL100
      temp: 45
      waterEfficiency: 4
      waterSaving: 77
    custom:
      program: eco_bldc
    parameters:
      checkUpStatus: 0
      delayTime: 0
      extraDry: 0
      halfLoad: 0
      onOffStatus: 1
      openDoor: 0
      prCode: 8
      prPosition: 1
      prStr: 0
  statistics:
    drawerCleaning:
      count: 410
      percentage: 410
      remaining: -310
      tot: 100
    drumCleaning:
      count: 410
      percentage: 410
      remaining: -310
      tot: 100
    filterCleaning:
      count: 410
      percentage: 2733
      remaining: -395
      tot: 15
    lastCheckup: None
    mostUsedPrograms:
      - count: 316
        prCode: 8
        prPosition: 1
        programName: PROGRAMS.DW.ECO_BLDC
        programType: D
      - count: 83
        prCode: 10
        prPosition: 4
        programName: PROGRAMS.DW.IOT_FAIRY_QUICK_CYCLE
      - count: 13
        prCode: 10
        prPosition: 4
        programName: PROGRAMS.DW.RAPID_59
      - count: 10
        prCode: 10
        prPosition: 4
        programName: PROGRAMS.DW.undefined
        programType: D
      - count: 6
        prCode: 3
        prPosition: 8
        programName: PROGRAMS.DW.INTENSIVE_RAPID
    programsCounter: 428
    resultCode: 0
    sprayArmsCleaning:
      count: 410
      percentage: 410
      remaining: -310
      tot: 100
    tabs: 0
    temperatureUsage:
      temp45to55: -1
      temp60to65: -997
      temp70to75: -8
  stopProgram:
    parameters:
      onOffStatus: 0
commands:
  settings:
    buzzerDisabled:
      max: 1
      min: 0
      step: 1
    category:
      - setConfig
      - setParameters
    lastCycleSavingStatus:
      max: 1
      min: 0
      step: 1
    waterHard:
      max: 7
      min: 0
      step: 1
  startProgram:
    delayTime:
      max: 1410
      min: 0
      step: 30
    ecoIndexOpt3:
      - eyixijo1fq==
    ecoIndexOpt4:
      - eyixijoyldv9
    ecoIndexOpt5:
      - eyixijo1fq==
    energyLabel:
      max: 5
      min: 0.5
      step: 1
    extraDry:
      max: 1
      min: 0
      step: 1
    halfLoad:
      max: 1
      min: 0
      step: 1
    openDoor:
      max: 1
      min: 0
      step: 1
    program:
      - Auto Sensor
      - Rapid 29' 50°C
      - Rapid 39' 60°C
      - auto_sensor_soil
      - auto_universal_plus_soil
      - auto_universal_soil
      - dishwasher_care
      - eco_bldc
      - gentle_wash
      - glassware
      - hygiene_plus
      - intensive_rapid
      - iot_baby_care
      - iot_breakfast
      - iot_checkup
      - iot_china_crystals
      - iot_cocktail_glasses_soil
      - iot_daily_care_soil
      - iot_dinner_for_two_soil
      - iot_dreft_quick_cycle
      - iot_extra_hygiene
      - iot_fairy_quick_cycle
      - iot_happy_hour
      - iot_party_soil
      - iot_pizza_menu_soil
      - iot_plastic_tupperware
      - iot_porcelain
      - iot_pot_&_pans_soil
      - iot_power_mix_wash_soil
      - iot_pyrex_and_glassware
      - iot_single
      - iot_super_flash
      - iot_super_wash
      - iot_turbopower
      - iot_voice_automatic
      - iot_voice_eco
      - iot_voice_prewash
      - iot_voice_rapid_59
      - iot_voice_universal
      - iot_wok_grids_maxi_pans_soil
      - prewash
      - rapid_29
      - rapid_39
      - rapid_59
      - steam_plus
      - ultra_silence
    programFamily:
      - dashboard
      - guided
      - dashboard_guided
    remainingTime:
      max: 160
      min: 145
      step: 15
    temp:
      max: 60
      min: 50
      step: 10
rules:
  startProgram:
    extraDry:
      1:
        ecoExpress: 0
    halfLoad:
      1:
        ecoExpress: 0
        opt8: 0
pyhOnVersion: 0.13.0
```

It seems mine says the same as yours for chipset.
