### ISSUE TITLE
Answer handler error, msg=01, answ=03, err=7

### ISSUE THREAD

**Issue by sunshine-hass** [paveldn/haier-esphome#39]
The air conditioner is functioning but cannot be controlled

INFO ESPHome 2023.12.9
INFO Reading configuration /config/esphome/55.yaml...
WARNING GPIO5 is a strapping PIN and should only be used for I/O with care.
Attaching external pullup/down resistors to strapping pins can cause unexpected failures.
See https://esphome.io/guides/faq.html#why-am-i-getting-a-warning-about-strapping-pins
INFO Detected log level for Haier protocol: DEBUG
INFO Starting log output from 192.168.5.200 using esphome API
INFO Successfully connected to haier @ 192.168.5.200 in 0.007s
INFO Successful handshake with haier @ 192.168.5.200 in 0.094s
[16:51:26][I][app:102]: ESPHome version 2023.12.9 compiled on Feb  4 2024, 12:21:24
[16:51:26][C][logger:439]: Logger:
[16:51:26][C][logger:440]:   Level: DEBUG
[16:51:26][C][logger:441]:   Log Baud Rate: 115200
[16:51:26][C][logger:443]:   Hardware UART: UART0
[16:51:26][C][uart.arduino_esp32:137]: UART Bus 1:
[16:51:26][C][uart.arduino_esp32:138]:   TX Pin: GPIO17
[16:51:26][C][uart.arduino_esp32:139]:   RX Pin: GPIO5
[16:51:26][C][uart.arduino_esp32:141]:   RX Buffer Size: 256
[16:51:26][C][uart.arduino_esp32:143]:   Baud Rate: 9600 baud
[16:51:26][C][uart.arduino_esp32:144]:   Data Bits: 8
[16:51:26][C][uart.arduino_esp32:145]:   Parity: NONE
[16:51:26][C][uart.arduino_esp32:146]:   Stop bits: 1
[16:51:26][C][haier.climate:239]: Haier Climate 'Haier AC'
[16:51:26][C][haier.climate:240]:   Device communication status: established
[16:51:26][C][haier.climate:298]:   Protocol version: hOn
[16:51:26][C][haier.climate:299]:   Control method: 1
[16:51:26][C][haier.climate:301]:   Device protocol version: E++2.18
[16:51:26][C][haier.climate:302]:   Device software version: 20220902
[16:51:27][C][haier.climate:303]:   Device hardware version: 00000000
[16:51:27][C][haier.climate:304]:   Device name: U-BAC
[16:51:27][C][haier.climate:310]:   Device features: crc
[16:51:27][C][haier.climate:311]:   Active alarms: 00 00 00 00 00 00 00 00
[16:51:27][C][ethernet:222]: Ethernet:
[16:51:27][C][ethernet:354]:   IP Address: 192.168.5.200
[16:51:27][C][ethernet:355]:   Hostname: 'haier'
[16:51:27][C][ethernet:356]:   Subnet: 255.255.255.0
[16:51:27][C][ethernet:357]:   Gateway: 192.168.5.2
[16:51:27][C][ethernet:362]:   DNS1: 192.168.5.2
[16:51:27][C][ethernet:363]:   DNS2: 0.0.0.0
[16:51:27][C][ethernet:383]:   MAC Address: A0:A3:B3:23:B0:7B
[16:51:27][C][ethernet:388]:   Is Full Duplex: YES
[16:51:27][C][ethernet:393]:   Link Speed: 100
[16:51:27][C][ethernet:225]:   Power Pin: 16
[16:51:27][C][ethernet:227]:   MDC Pin: 23
[16:51:27][C][ethernet:228]:   MDIO Pin: 18
[16:51:27][C][ethernet:229]:   Type: LAN8720
[16:51:27][C][ethernet:230]:   PHY addr: 1
[16:51:27][C][mdns:115]: mDNS:
[16:51:27][C][mdns:116]:   Hostname: haier
[16:51:27][C][ota:097]: Over-The-Air Updates:
[16:51:27][C][ota:098]:   Address: haier.local:3232
[16:51:27][C][ota:101]:   Using Password.
[16:51:27][C][api:139]: API Server:
[16:51:27][C][api:140]:   Address: haier.local:6053
[16:51:27][C][api:142]:   Using noise encryption: YES
[16:51:30][D][haier.protocol:019]: Sending frame: type 01, data: 4D 01
[16:51:30][D][haier.protocol:019]: Frame found: type 02, data: 6D 01 07 02 47 00 00 03 14 00 00 00 00 00 00 00 00 07 01 23 2A 00 55 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[16:51:30][D][haier.climate:775]: HVAC Mode = 0x2
[16:51:30][D][haier.climate:776]: Fan speed Status = 0x7
[16:51:30][D][haier.climate:777]: Horizontal Swing Status = 0x0
[16:51:30][D][haier.climate:778]: Vertical Swing Status = 0x2
[16:51:30][D][haier.climate:779]: Set Point Status = 0x7
[16:51:35][D][climate:011]: 'Haier AC' - Setting
[16:51:35][D][climate:015]:   Mode: FAN_ONLY
[16:51:35][D][Control:327]: Control call
[16:51:35][W][haier.climate:333]: New settings come faster then processed!
[16:51:35][I][haier.climate:396]: Sending control packet, queue size 1
[16:51:35][D][haier.protocol:019]: Sending frame: type 01, data: 60 01 08 06 C4 00 02 83 14 00 00 00
[16:51:35][D][haier.protocol:019]: Frame found: type 03, data: 00 01
[16:51:35][W][haier.protocol:013]: Answer handler error, msg=01, answ=03, err=7
[16:51:37][D][haier.protocol:019]: Sending frame: type 01, data: 4D 01
[16:51:37][D][haier.protocol:019]: Frame found: type 02, data: 6D 01 07 02 47 00 00 03 14 00 00 00 00 00 00 00 00 07 01 23 2A 00 55 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[16:51:37][D][haier.climate:775]: HVAC Mode = 0x2
[16:51:37][D][haier.climate:776]: Fan speed Status = 0x7
[16:51:37][D][haier.climate:777]: Horizontal Swing Status = 0x0
[16:51:37][D][haier.climate:778]: Vertical Swing Status = 0x2
[16:51:37][D][haier.climate:779]: Set Point Status = 0x7
[16:51:38][D][climate:011]: 'Haier AC' - Setting
[16:51:38][D][climate:040]:   Target Temperature: 27.00
[16:51:38][D][Control:327]: Control call
[16:51:38][W][haier.climate:333]: New settings come faster then processed!
[16:51:38][I][haier.climate:396]: Sending control packet, queue size 1
[16:51:38][D][haier.protocol:019]: Sending frame: type 01, data: 60 01 08 06 C4 00 02 83 14 00 00 00
[16:51:38][D][haier.protocol:019]: Frame found: type 03, data: 00 01
[16:51:38][W][haier.protocol:013]: Answer handler error, msg=01, answ=03, err=7
[16:51:42][D][haier.protocol:019]: Sending frame: type 01, data: 4D 01
[16:51:42][D][haier.protocol:019]: Frame found: type 02, data: 6D 01 07 02 47 00 00 03 14 00 00 00 00 00 00 00 00 07 01 23 2A 00 55 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[16:51:42][D][haier.climate:775]: HVAC Mode = 0x2
[16:51:42][D][haier.climate:776]: Fan speed Status = 0x7
[16:51:42][D][haier.climate:777]: Horizontal Swing Status = 0x0
[16:51:42][D][haier.climate:778]: Vertical Swing Status = 0x2
[16:51:42][D][haier.climate:779]: Set Point Status = 0x7
[16:51:47][D][haier.protocol:019]: Sending frame: type 01, data: 4D 01
[16:51:47][D][haier.protocol:019]: Frame found: type 02, data: 6D 01 07 02 47 00 00 03 14 00 00 00 00 00 00 00 00 07 01 23 2A 00 55 00 00 04 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
[16:51:47][D][haier.climate:775]: HVAC Mode = 0x2
[16:51:47][D][haier.climate:776]: Fan speed Status = 0x7
[16:51:47][D][haier.climate:777]: Horizontal Swing Status = 0x0
[16:51:47][D][haier.climate:778]: Vertical Swing Status = 0x2
[16:51:47][D][haier.climate:779]: Set Point Status = 0x7

uart:
  tx_pin: 17
  rx_pin: 5
  baud_rate: 9600
  id: ac_port

climate:
  - platform: haier
    id: haier_ac
    protocol: hOn
    name: Haier AC
    uart_id: ac_port
    # wifi_signal: true
    beeper: true
    display: true
    outdoor_temperature:
      name: Haier AC outdoor temperature
    visual:
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    supported_modes:
    - 'OFF'
    - HEAT_COOL
    - COOL
    - HEAT
    - DRY
    - FAN_ONLY
    supported_swing_modes:
    - 'OFF'
    - VERTICAL
    - HORIZONTAL
    - BOTH

**Comment by sunshine-hass** [comment]
Hello!
Is it because the protocol is not supported or because my code configuration is wrong?

**Comment by sunshine-hass** [comment]
Hello!
Thank you very much for your reply.
After adding the option, you can use most functions. However, after using the FAN_ONLY mode, Answer handler error, msg=01, answ=03, err=7 appears. The module must be restarted before it can be controlled normally. Now check whether there are any configuration problems.

**Comment by paveldn** [comment]
@sunshine-hass ,
I'm glad it helped. 
Usually, answer 03 from AC means error. Keep in mind that this way of controlling AC using SET_SINGLE_PARAMETER is not very common. So not everything is 100% tested. Can you make logs of the situation for me?

**Comment by sunshine-hass** [comment]
I need to provide useful information

**Comment by sunshine-hass** [comment]
[logs_haier2_logs.txt](https://github.com/paveldn/haier-esphome/files/14211545/logs_haier2_logs.txt)
control_packet_size:18
When set to the above parameters, the indoor temperature will be displayed
When using the Haier Smart APP, the indoor temperature will be displayed.
Can the error be fixed based on the above log?

**Comment by paveldn** [comment]
Thanks. Now more or less clear what is happening. Your AC is answering 03 (which most likely indicates that it is not a supported feature) to command 0x19 which is a quiet mode setting. Quiet mode should be disabled in "Fan only" mode. Not clear why this command was sent multiple times it should be only one time. Was this just a one-time attempt or did you try to do it multiple times? I see every time after "Answer handler error" "Control call", messages that it indicates that somebody outside of the component causing some changes but I don't know if it is you, Home Assistant, or ESPHome. Will see what I can do. I will come to you when I will have something to test.

**Comment by sunshine-hass** [comment]
As long as there is error support, it cannot be controlled normally. The multiple errors you see are because when the error was triggered for the first time, I tried to use other functions, which caused multiple errors.

**Comment by paveldn** [comment]
Can you try this branch: https://github.com/paveldn/haier-esphome/tree/no_silent_test ?
you will need to add the following config to the haier climate section:
```
  supported_presets:
    - BOOST
    - SLEEP
```

Let me know if it helps. It will remove the ECO preset from your climate (which is anyway not supported) and suppress the command that causes problems.

**Comment by sunshine-hass** [comment]
Thank you very much for your reply.
1. Now this configuration function is basically normal, but the following prompt appears whether it needs to be repaired.
[17:15:40][W][component:214]: Component haier.climate took a long time for an operation (0.05 s).
[17:15:40][W][component:215]: Components should block for at most 20-30ms.
2. However, setting the temperature when using FAN_ONLY mode will still cause Answer handler error, msg=01, answ=03, err=7. The temperature cannot be set on the remote control when using FAN_ONLY. Is this possible?
3. The wind speed status is out of sync with when using the remote control. Neither low nor high can respond to the status controlled by the remote control. Can it be repaired?
fan_modes:
   -auto
   -low
   -medium
   -high
The configuration is now as follows:
external_components:
  - source:
      type: git
      url: https://github.com/paveldn/haier-esphome
      ref: no_silent_test
    components: [haier]
climate:
  - platform: haier
    id: haier_ac
    protocol: hOn
    name: Haier AC999 
    uart_id: ac_port
    # wifi_signal: true          # Optional, default true, enables WiFI signal transmission from ESP to AC
    beeper: true            # false Optional, default true, disables beep on commands from ESP
    display: true              # Optional, default true, can be used to turn off LED display
    control_method: SET_SINGLE_PARAMETER
    # control_packet_size: 18
    # control_method: SET_GROUP_PARAMETERS  
    answer_timeout: 200ms      # Optional, request answer timeout, can be used to increase the timeout
                                # for some ACs that have longer answer delays
    visual:                     # Optional, you can use it to limit min and max temperatures in UI (not working for remote!)
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    supported_modes:            # Optional, can be used to disable some modes if you don't need them
    - 'OFF'
    - HEAT_COOL
    - COOL
    - HEAT
    - DRY
    - FAN_ONLY
    supported_presets:          # Optional, can be used to disable some presets if your AC does not support it
    # - BOOST
    # - SLEEP
    supported_swing_modes:      # Optional, can be used to disable some swing modes if your AC does not support it
    # - 'OFF'
    # - VERTICAL
    # - HORIZONTAL
    # - BOTH

**Comment by paveldn** [comment]
Hi @sunshine-hass 

> Component haier.climate took a long time for an operation (0.05 s).

Sorry, can't fix this. I optimized my component as much as possible. My investigation shows that most of the delay is coming from 2 things: 
1. logging system - the more you log the slower your component. So I would suggest setting the logging level to WARN once you finish configuring your AC. It should ease the problem but not fix it completely.
2. parent component function calls. When there is a change of state for AC my component calls the parent component (which is Climate) to update status. That is causing all updates of web UI, publishing state to the home assistant, etc. This call is very slow and most likely that is the reason of warn messages you see. I can't do anything here it is not just a problem of my component but most of the components.

> However, setting the temperature when using FAN_ONLY mode will still cause Answer handler error, msg=01, answ=03, err=7. The temperature cannot be set on the remote control when using FAN_ONLY. Is this possible?

This one is easy to fix, will do it later today.

> The wind speed status is out of sync with when using the remote control. Neither low nor high can respond to the status controlled by the remote control. Can it be repaired?

That one is strange. Maybe your AC not updating the status correctly after using the remote. I will need logs from you. Just make sure you have at least 20 seconds of logs before you use the remote and 20 seconds after. And let me know which mode was before the change and which after.

**Comment by paveldn** [comment]
Please, check the latest commit on https://github.com/paveldn/haier-esphome/tree/no_silent_test I removed setting temp in fan only mode.

**Comment by paveldn** [comment]
No feedback I assume the issue is solved. The solution is merged in the dev branch and will be included in next pull request to ESPHome

**Comment by d22cva** [comment]
Hello! I have the same problem as in the first post. When I select any action I get "Answer handler error, msg=01, answ=03, err=7". The module from the air conditioner kit is as pictured in the description on esphome.io in the "Haier Climate" section. I use a Wemos D1 mini board. When loading the firmware for hOn, I see the status of the compressor when I control the remote control. I conclude that the board was assembled correctly. Some parameters are displayed, but I'm not sure what's correct. I tried flashing the smartair2 protocol, but didn’t see any parameters.

On hOn firmware:
- I tried to swap Rx and Tx - no luck.
- I tried to add control_method: SET_SINGLE_PARAMETER in the config - no success.
- I tried adding control_packet_size: 18 - no success.
- I tried firmware for Wemos D1 mini from the DEV and EXPEREMETAL branches - no success.

Judging by the posts above, the problem has been resolved. Maybe I'm doing something wrong? I would appreciate your help!
I am writing in a language that is not my native one! Thanks for understanding!

**Comment by d22cva** [comment]
> Никаких отзывов, думаю, проблема решена. Решение добавлено в ветку разработки и будет включено в следующий запрос на включение в ESPHome.

Hello! I have the same problem as in the first post. When I select any action I get "Answer handler error, msg=01, answ=03, err=7". The module from the air conditioner kit is as pictured in the description on esphome.io in the "Haier Climate" section. I use a Wemos D1 mini board. When loading the firmware for hOn, I see the status of the compressor when I control the remote control. I conclude that the board was assembled correctly. Some parameters are displayed, but I'm not sure what's correct. I tried flashing the smartair2 protocol, but didn’t see any parameters.

On hOn firmware:

I tried to swap Rx and Tx - no success.
I tried to add control_method: SET_SINGLE_PARAMETER in the config - no success.
I tried adding control_packet_size: 18 - no success.
I tried firmware for Wemos D1 mini from the DEV and EXPEREMETAL branches - no success.
Judging by the posts above, the problem has been resolved. Maybe I'm doing something wrong? I would appreciate your help!
I am writing in a language that is not my native one! Thanks for understanding!

**Comment by paveldn** [comment]
Hi @d22cva,

Я говорю по русски так что можете использовать его. Чтобы помочь вам мне для начала нужен лог вашего устройства. При этом попробуйте что-то поменять из веб интерфейса (или Home assistant). Какая у вас модель кондиционера?

**Comment by d22cva** [comment]
> Hi @d22cva,
> 
> Я говорю по русски так что можете использовать его. Чтобы помочь вам мне для начала нужен лог вашего устройства. При этом попробуйте что-то поменять из веб интерфейса (или Home assistant). Какая у вас модель кондиционера?
 
Замечательно! Модель кондиционера Casarte  внутренний блок CAS35MW1/R3-W, наружный 1U35MW1/R3. Родной Wi-Fi модуль ESP32-for-Haier_v1.1 работает через приложение EVO. Я думаю это протокол hOn. Родной модуль не стал перешивать так как кондиционер на гарантии. Пробовал протокол smartair2, но на нём по моему мнению вообще связи нет с кондиционером. На протоколе hOn получаю хоть какие-то значения. Было замечено если с пульта включить, например, охлаждение , то параметр "Haier AC Compressor Status" изменяет своё значение на ON и наоборот если выключить с пульта. На действия в веб-интерфейсе не реагирует, вернее в логе веб-интерфейса получаю сообщение "Answer handler error, msg=01, answ=03, err=7"  .Подскажи как правильно снять лог? Достаточно будет скопировать примитивно из веб-интерфейса esphome?

**Comment by d22cva** [comment]
Прилагаю логи, которые смог скопировать с веб-интерфейса. Во всех случаях параметр control_method был убран из конфига. Если как-то поможет значение Compressor Status соответствовало действительности только при control_packet_size по умолчанию. В остальных случаях этот параметр не менялся. Некоторые параметры что-то отображали, но они были далеко от действительности.

[control_packet_size_12_Action_in_Web.txt](https://github.com/user-attachments/files/15594558/control_packet_size_12_Action_in_Web.txt)
[control_packet_size_12_Remote_action_OFF.txt](https://github.com/user-attachments/files/15594559/control_packet_size_12_Remote_action_OFF.txt)
[control_packet_size_12_Start.txt](https://github.com/user-attachments/files/15594560/control_packet_size_12_Start.txt)
[control_packet_size_14_Action_in_Web.txt](https://github.com/user-attachments/files/15594561/control_packet_size_14_Action_in_Web.txt)
[control_packet_size_14_Remote_action_ON.txt](https://github.com/user-attachments/files/15594562/control_packet_size_14_Remote_action_ON.txt)
[control_packet_size_14_Start.txt](https://github.com/user-attachments/files/15594563/control_packet_size_14_Start.txt)
[default_parametrs_Action.txt](https://github.com/user-attachments/files/15594564/default_parametrs_Action.txt)
[default_parametrs_Remote_action_ON.txt](https://github.com/user-attachments/files/15594565/default_parametrs_Remote_action_ON.txt)
[default_parametrs_Start.txt](https://github.com/user-attachments/files/15594566/default_parametrs_Start.txt)

**Comment by paveldn** [comment]
Это что-то совсем новое. Я таких пакетов еще не видел. Протокол тот же что и hOn но пакет статуса совсем другой. Тут нужно копать с самого начала. Боюсь что простыми подстройками тут не обойдешся. 
Тут все зависит насколько вы полны решимости добавить его в Home Assistant. Потому что тут нужно єкспериментировать и анализировать, анализировать и єксперементировать. Анализировать я могу и сам но вот делать эксперименты прийдется вам.

**Comment by d22cva** [comment]
Готов попытаться!

**Comment by paveldn** [comment]
> Готов попытаться!

Возможно все не так плохо как я думал вгачале. Похоже паект статуса просто имеет вначале странный блрк состоящий почти полностью из нулей. Если его пропустить по крайней мере чтение состояния долэно работать. А вот что делать с управлкнием прийжктся разбираться. Я немного приболел поэтому сегодня не могу но постараюсь завтра написать инструкцию как подготовить ESP к экспериментам. А пока можете показать свою конфигурацию? Только часть насчет кондиционера.

**Comment by d22cva** [comment]
Поправляйтесь! Буду пытаться помочь чем смогу. Единственное могу этим заниматься не всегда из-за своей работы.
Мой конфиг по большому счёту аналогичен вашему из репозитория master. Оставил прошивку на которой меняется статус Compressor Status. Ещё хочу отметить, может кому-то поможет, что на прошивках из ветки dev и experemental почему-то зависает esp при включенных компонентах self_cleaning_button и steri_cleaning_button, т.е. в веб-интерфейсе отображается 2-5 параметра и лог не идёт. Веб-интерфейс не отзывчив и будто зависает. Стоит отключить именно self_cleaning_button и steri_cleaning_button как веб-интерфейс начинает работать как положено. На прошивке из ветки master на такое поведение я наткнулся только 1 раз и для лучшей работы на всякий случай отключил эти компоненты. 


**haier_hon.yaml**
```
climate:
  - platform: haier
    id: ${device_id}
    protocol: hOn
    name: ${device_name}
    uart_id: ${uart_id}
    wifi_signal: ${send_wifi}   # Optional, default true, enables WiFI signal transmission from ESP to AC
    #answer_timeout: 200ms      # TEST. Default 200ms
    #control_packet_size: 14    # TEST. Default 10
    #control_method: SET_SINGLE_PARAMETER           # TEST. Default SET_GROUP_PARAMETERS 
    beeper: true                # Optional, default true, disables beep on commands from ESP
    visual:                     # Optional, you can use it to limit min and max temperatures in UI (not working for remote!)
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 
        target_temperature: 1
        current_temperature: 0.5
    supported_modes:            # Optional, can be used to disable some modes if you don't need them
      - 'OFF'                     # always available
      - HEAT_COOL                 # always available
      - COOL
      - HEAT
      - DRY
      - FAN_ONLY
    supported_swing_modes:      # Optional, can be used to disable some swing modes if your AC does not support it
      - 'OFF'
      - VERTICAL
      - HORIZONTAL
      - BOTH
    supported_presets:          # Optional, can be used to disable some presets if your AC does not support it
      - ECO
      - BOOST
      - SLEEP
    # Next two triggers calling Home Assistant services to notify user about alarms triggered by AC
    # this functionality is disabled by default. To enable it check "Allow the device to make Home Assistant service calls"
    # checkbox in Home Assistant's device settings
    on_alarm_start:
      then:
        - homeassistant.service:
            service: logbook.log
            data:
              domain: climate
              name: ${device_name}
            data_template:
              message: "Alarm activated ({{ alarm_code }}): {{alarm_message}}" 
            variables:
              alarm_message: !lambda "return message;"
              alarm_code: !lambda "return code;"
        - homeassistant.service:
            service: notify.persistent_notification
            data:
              title: "${device_name}: alarm activated"
            data_template:
              message: "Code: {{ alarm_code }}, message: \"{{ alarm_message }}\""
            variables:
              alarm_message: !lambda "return message;"
              alarm_code: !lambda "return code;"
    on_alarm_end:
      then:
        - homeassistant.service:
            service: logbook.log
            data:
              domain: climate
              name: ${device_name}
            data_template:
              message: "Alarm deactivated ({{ alarm_code }}): {{alarm_message}}" 
            variables:
              alarm_message: !lambda "return message;"
              alarm_code: !lambda "return code;"

```
