### ISSUE TITLE
Fan mode

### ISSUE THREAD

**Issue by uKL** [paveldn/haier-esphome#44]
Is it expected that fan mode and swing mode are not visible with esp32-haier-module.yaml?

**Comment by paveldn** [comment]
@uKL You need to provide more information: visible where? Home Assistant? Web Interface? What kind of config you are using?
Usually, fan and swing modes will not be visible in the web interface just in Home Assistant.

**Comment by uKL** [comment]
Web Interface. This is my config
```

substitutions:
  device_name: Haier AC
  device_id: haier_climate
  uart_id: ac_port
  send_wifi: "true"

esphome:
  name: haier
  name_add_mac_suffix: true
  platformio_options:
    upload_speed: 115200

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 8080
  local: true
  auth:
    username: admin
    password: !secret api_pwd

uart:
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  id: ${uart_id}

logger:
  level: DEBUG

packages:
  local_haier: !include configs/external_components/local_haier.yaml
  haier_base: !include .haier-hon-base.yaml 

```

I'm gonna use it with MQTT in the long run, without the Home Assistant :)

This is what I see in the Web Intetrface.
<img width="931" alt="Zrzut ekranu 2024-06-19 o 07 19 47" src="https://github.com/paveldn/haier-esphome/assets/2377962/c5b0468d-330f-4317-a19a-32929a16c72a">

Is it possible to add fan and swing like the manual direction control?
