### ISSUE TITLE
i need help to intall it :)

### ISSUE THREAD

**Issue by lakusz1github** [paveldn/haier-esphome#46]
Hi

I'm a little noob, and probably i made some stupid mistake, which i not see it.

I use D1 mini, but i have SmartAir2 version of climate, so i "merge" smartair2-esp8266.yaml and wemos_d1_mini.yaml and put it on my d1_mini device, i also put file .haier-smartair2-base.yaml and folder configs to HA\esphome\*

i get all the time `"Answer timeout for command 01, phase SENDING_FIRST_STATUS_REQUEST"`

i also add to file \configs\climate\haier_smartair2.yaml
```
climate:
  - platform: haier
    ...
    answer_timeout: 200ms
    ...
```

from https://github.com/paveldn/haier-esphome/issues/28 

how install this integration properly in my HA ?

Thanks in advance :)

**Comment by paveldn** [comment]
Hi. First of all can you provide your full configuration (of course replace all passwords, keys and IPs with xx)? Also please check that UART port config is correct (same pins as in old working version of integration)

**Comment by lakusz1github** [comment]
```
substitutions:
  device_name: Haier AC
  device_id: haier_climate
  uart_id: ac_port
  send_wifi: "true"

esphome:
  name: esp-haier
#  name_add_mac_suffix: true
  friendly_name: esp-Haier

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: 

ota:
  platform: esphome
  password: 

web_server:
  port: 8080
 
wifi:
  ssid: 
  password: 

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp-Haier Fallback Hotspot"
    password: 

captive_portal:
 
uart:
  - id: ${uart_id}
    baud_rate: 9600
    # You can also use pins 15 (TX) and 13 (RX)
    tx_pin: 1
    rx_pin: 3


packages:
#  haier_base: !include .haier-hon-base.yaml
  haier_base: !include .haier-smartair2-base.yaml
```
