### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by xppepel** [paveldn/haier-esphome#47]
Hi.
I try to bild *.bin file.
Using examples for YAML file and it compiling to *.bin.
But if I uncomment package block HA cant to connect(Connection refused) and show error "uoy fogot api: in yaml" 

With it connect - 
```
substitutions:
  device_name: Haier AC Living Room
  device_id: haier_ac_lv
  uart_id: ac_port
  send_wifi: "true"

esphome:
  name: haierlv
  name_add_mac_suffix: true

esp8266:
  board: esp01_1m

wifi:
  ssid: 
  password: 
  power_save_mode: none

uart:
  - id: ${uart_id}
    baud_rate: 9600
    # You can also use pins 15 (TX) and 13 (RX)
    tx_pin: 1
    rx_pin: 3

logger:
  level: DEBUG
  baud_rate: 0  

# Enable Home Assistant API
api:

web_server:
```

And can't connect, when I add to YAML:
```
packages:
  local_haier: !include configs/external_components/local_haier.yaml
  haier_base: !include .haier-hon-base.yaml
```
