### ISSUE TITLE
Get no response on UART

### ISSUE THREAD

**Issue by balloob** [paveldn/haier-esphome#50]
Hey Pavel,

Thanks for all your work on integrating Haier devices 😄 

I am trying to use the Haier component in ESPHome with an [`SLWF-01`](https://smartlight.me/smart-home-devices/wifi-devices/wifi-dongle-air-conditioners-midea-idea-electrolux-for-home-assistant) connected to a Haier split unit model `AS25S2SF2FA-1` (manuf Nov. 2019).

I am using the SmartAir2 protocol but I am unable to get any messages back. Now I am 99% sure it's my fault, but even with the help of Jesse, I wasn't able to figure it out 😞 

```yaml
logger:
  baud_rate: 0

uart:
  tx_pin: 12
  rx_pin: 14
  baud_rate: 9600
  debug:
    direction: BOTH
    dummy_receiver: false
    after:
      delimiter: "\n"
    sequence:
      - lambda: UARTDebug::log_hex(direction, bytes, ' ');

climate:
  - platform: haier
    id: haier_ac
    protocol: smartair2
    name: "${friendly_name}"
```

Now I once had a soldered version using [this custom component](https://github.com/MiguelAngelLV/esphaier) that I remember did work partially. I tried mimicking the message it sends (it's very similar), but also that gives me no response:

```yaml
button:
  - platform: uart
    name: Do the poll
    id: midea_display_toggle
    data: [255, 255, 10, 0, 0, 0, 0, 0, 1, 1, 77, 1, 90]
```

Can you see at a glance what's going wrong? 

Thanks,
Paulus
