### ISSUE TITLE
ESP32 haier module doesn't connect to wifi after flashing

### ISSUE THREAD

**Issue by Napalmcold** [paveldn/haier-esphome#9]
Hi! I got 3 Haier Flexis units with those modules. The mobile app is called EVO, not hOn and not smartair2.
Successfully made a backup following your guide. But after flashing the module through the esphome addon in home assistant, it doesn't show up on network. I tried different yaml configs from your repository, but everytime same result: no connection to wifi network and no falback wifi hotspot. 
After fIashing I get these logs while connected to serial without flashing mode:

```
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57

rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
flash read err, 1000
ets_main.c 371 
ets Jun  8 2016 00:22:57
```

When I flash it back to the original firmware it works well again.
What am I doing wrong?

**Comment by paveldn** [comment]
Hi @Napalmcold ,

First of all great that you have made a backup. Just keep in mind that there are unique keys for every module so if you have three of them you will need to make a backup per module and remember which backup from which module.
About your problem: 
I was not able to find the EVO app in the play store. Apparently, it is some regional version of the application unavailable in my region. Anyway, the message you see is not from ESPhome itself but from the bootloader and it is a flash reading error. Something should be different about your hardware. Did you change something in the esp32 section of your yaml config? I suppose not just need to make sure :) 
To check your hardware I need to see your chip id. Please, put the device in flashing mode (the same way you did for making a backup) and run esptool with the following command:
`python esptool.py --port <port_name> chip_id`
and post your results here.  
It should be something like this:
```
Detecting chip type... ESP32
Chip is ESP32-S0WD (revision 1)
Features: WiFi, BT, Single Core, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: XX:XX:XX:XX:XX:XX
Uploading stub...
Running stub...
Stub running...
Manufacturer: 20
Device: 4016
Detected flash size: 4MB

```

I am interested in chip type and flash size. You can remove your board MAC it is not needed.

**Comment by Napalmcold** [comment]
> Hi @Napalmcold ,
> 
> First of all great that you have made a backup. Just keep in mind that there are unique keys for every module so if you have three of them you will need to make a backup per module and remember which backup from which module. About your problem: I was not able to find the EVO app in the play store. Apparently, it is some regional version of the application unavailable in my region. Anyway, the message you see is not from ESPhome itself but from the bootloader and it is a flash reading error. Something should be different about your hardware. Did you change something in the esp32 section of your yaml config? I suppose not just need to make sure :) To check your hardware I need to see your chip id. Please, put the device in flashing mode (the same way you did for making a backup) and run esptool with the following command: `python esptool.py --port <port_name> chip_id` and post your results here. It should be something like this:
> 
> ```
> Detecting chip type... ESP32
> Chip is ESP32-S0WD (revision 1)
> Features: WiFi, BT, Single Core, VRef calibration in efuse, Coding Scheme None
> Crystal is 40MHz
> MAC: XX:XX:XX:XX:XX:XX
> Uploading stub...
> Running stub...
> Stub running...
> Manufacturer: 20
> Device: 4016
> Detected flash size: 4MB
> ```
> 
> I am interested in chip type and flash size. You can remove your board MAC it is not needed.

Hi, Pavel!

First of all, thanks for your respond, I much appreciate that.

Here is the config, I've only changed external components path to github:

```
substitutions:
  device_name: Haier AC
  device_id: haier_climate
  uart_id: ac_port 
  send_wifi: "true"

esphome:
  name: haier
  friendly_name: Haier
  name_add_mac_suffix: true

esp32:
  board: esp32dev
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  baud_rate: 9600
  tx_pin: 17
  rx_pin: 16
  id: ${uart_id}  

logger:
  level: DEBUG

external_components:
  - source: github://paveldn/ESP32-S0WD-Haier@dev
    
api:
  encryption:
    key: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

ota:
  password: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

climate:
  - platform: haier
    id: ${device_id}
    protocol: hOn
    name: ${device_name} 
    uart_id: ${uart_id}
    wifi_signal: ${send_wifi}   # Optional, default true, enables WiFI signal transmission from ESP to AC
    beeper: true                # Optional, default true, disables beep on commands from ESP
    outdoor_temperature:        # Optional, outdoor temperature sensor
      name: ${device_name} outdoor temperature
    visual:                     # Optional, you can use it to limit min and max temperatures in UI (not working for remote!)
      min_temperature: 16 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    supported_modes:            # Optional, can be used to disable some modes if you don't need them
    - 'OFF'                     # always available
    - AUTO                      # always available
    - COOL
    - HEAT
    - DRY
    - FAN_ONLY
    supported_swing_modes:      # Optional, can be used to disable some swing modes if your AC does not support it
    - 'OFF'                     # always available
    - VERTICAL                  # always available
    - HORIZONTAL
    - BOTH

switch:
  - platform: template
    id: ${device_id}_display_switch
    name: ${device_name} display
    icon: mdi:led-on
    entity_category: config
    restore_state: yes
    lambda: |-
      return id(${device_id}).get_display_state();
    turn_on_action:
      climate.haier.display_on: ${device_id}
    turn_off_action:
      climate.haier.display_off: ${device_id}
  - platform: template
    id: ${device_id}_beeper_switch
    entity_category: config
    name: ${device_name} beeper
    icon: mdi:volume-high
    restore_state: yes
    lambda: |-
      return id(${device_id}).get_beeper_state();
    turn_on_action:
      climate.haier.beeper_on: ${device_id}
    turn_off_action:
      climate.haier.beeper_off: ${device_id}
  - platform: template
    id: ${device_id}_health_mode
    name: ${device_name} health mode
    icon: mdi:leaf
    restore_state: yes
    lambda: |-
      return id(${device_id}).get_health_mode();
    turn_on_action:
      climate.haier.health_on: ${device_id}
    turn_off_action:
      climate.haier.health_off: ${device_id}
  - platform: restart
    name: ${device_name} restart

select:
    # Vertical airflow direction setting. Works only if the vertical swing is off
    # You can remove this control if you don't need it
  - platform: template
    id: ${device_id}_vertical_direction
    name: ${device_name} airflow vertical
    entity_category: config
    icon: mdi:arrow-expand-vertical
    optimistic: true
    restore_value: true
    initial_option: Center 
    options:
      - Up
      - Center
      - Down
    on_value:
      then:
        - climate.haier.set_vertical_airflow:
           id: ${device_id}
           vertical_airflow: !lambda |-
             return esphome::haier::AirflowVerticalDirection(i);
    # Horizontal airflow direction setting. Works only if the horizontal swing is off
    # You can remove this control if you don't need it
  - platform: template
    id: ${device_id}_horizontal_direction
    name: ${device_name} airflow horizontal
    entity_category: config
    icon: mdi:arrow-expand-horizontal
    optimistic: true
    restore_value: true
    initial_option: Center 
    options:
      - Left
      - Center
      - Right
    on_value:
      then:
        - climate.haier.set_horizontal_airflow:
           id: ${device_id}
           horizontal_airflow: !lambda |-
             return esphome::haier::AirflowHorizontalDirection(i);
text_sensor:
  - platform: template
    name: ${device_name} cleaning status
    icon: mdi:spray-bottle
    lambda: return id(${device_id}).get_cleaning_status_text();

button:
  - platform: template
    name: ${device_name} start self cleaning
    icon: mdi:spray-bottle
    on_press:
      - climate.haier.start_self_cleaning: ${device_id}
  - platform: template
    name: ${device_name} start 56°C steri-cleaning
    icon: mdi:spray-bottle
    on_press:
      - lambda: id(${device_id}).start_steri_cleaning();
```

And herу is the chip_id command results::

```
esptool.py v4.5.1
Serial port COM6
Connecting.....
Detecting chip type... Unsupported detection protocol, switching and trying again...
Connecting...
Detecting chip type... ESP32
Chip is ESP32-S0WD (revision v1.0)
Features: WiFi, BT, Single Core, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: XX:XX:XX:XX:XX:XX
Uploading stub...
Running stub...
Stub running...
Warning: ESP32 has no Chip ID. Reading MAC instead.
MAC: XX:XX:XX:XX:XX:XX
Hard resetting via RTS pin...
```

**Comment by Napalmcold** [comment]
Also I've just noticed that the mac of module I'm trying to flash begins with 40:22:d8, while the other 2 modules have macs begining with CC:DB:A7. Looks like they are different. Later I'll try to flash one of those.

**Comment by paveldn** [comment]
MAC shouldn't be important I have a similar situation 3 of my modules starts with 24:A1:60 and 1 starts with C4:DD:57 and all of them worked fine. Your chip info looks the same, it should be OK. The only explanation I have is that Haier used in the new version of the module different flash mode. You can try to play with different modes, and add in esphome section the board_build.flash_mode field:
```
esphome:
  name: haier
  friendly_name: Haier
  name_add_mac_suffix: true
  platformio_options:
    board_build.flash_mode: dio
```
Use this link https://docs.platformio.org/en/latest/platforms/espressif32.html#flash-mode to see available options, and try them one by one. Let me know if it worked.
